#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre-push checks..."
npm run format
npm run lint
npm run test

# Create a temporary directory for the build output
BUILD_DIR=".next-validation"
mkdir -p $BUILD_DIR

NEXT_TELEMETRY_DISABLED=1 npx next build --no-lint --outdir $BUILD_DIR

rm -rf $BUILD_DIR
